### ISSUE TITLE
Fastbridge Feature

### ISSUE THREAD

**Issue by zan2009** [Pabsb/ZerodayClient#8]
So basically there is a free client that I sometimes use for legit hacking, it has this feature called Eagle. What I think you should add is a module that will essentially "Fastbridge" for you, you fastbridge by going backwards and then sneaking on the edge of the block to place another. You repeat this process to move fast while bridging over air, It would also be nice to have settings for it so that you could had a fail % so that you look a bit more legit. I hope you accept my suggestion, and hope I see it in the Build 9 release.

                      -  Neon

**Comment by Pabsb** [comment]
Please use the format and open a new issue.
